name: parsac
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.0
  - numpy=1.26.3
  - pip
  - python=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - torchvision=0.14.1
  - pip:
    - pylsd-nova
    - wandb

